import Head from 'next/head';
import { FunctionComponent, ReactElement } from 'react';
import { Container } from 'react-bootstrap';
import { AuthGuard } from '../components/auth-guard';
import { Navigation } from './navigation';

export const Layout : FunctionComponent = ({children}): ReactElement => {
	return(
		<AuthGuard>
			<Head>
				<title>Strixhaven Session Planner</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation/>
			<Container className='p-3'>
				{children}
			</Container>
		</AuthGuard>
	);
};