import { Container } from '@mui/material';
import Head from 'next/head';
import { FunctionComponent, ReactElement } from 'react';
import { Navigation } from './navigation';

export const Layout : FunctionComponent = ({children}): ReactElement => {
	return(
		<>
			<Head>
				<title>Strixhaven Session Planner</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<meta name='viewport' content='initial-scale=1, width=device-width' />
			</Head>
			<Navigation/>
			<Container maxWidth='sm'>
				{children}
			</Container>	
		</>
	);
};